server:
  port: ${PORT:8080}

spring:
  datasource:
    url: { DATABASE_URL }
    driver-class-name: org.postgresql.Driver
    username: { USERNAME }
    password: { PASSWORD }
    hikari:
      maximum-pool-size: 5